[package]
name = "pci"
version = "0.1.0"

[lib]
name = "pci"
path = "lib.rs"

[dependencies]
intrusive-collections = { version = "0.8.5", default-features = false, features = [ "nightly", "alloc" ]}
kernel = { path = "../../kernel" }
